// <auto-generated />
namespace HBM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PagerOnKindOfExpense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PagerOnKindOfExpense));
        
        string IMigrationMetadata.Id
        {
            get { return "202001132131347_PagerOnKindOfExpense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
